version: 2
jobs:
    build:
        docker:
            - image: theorangeone/docker-pandoc
        working_directory: ~/pirate-islands2
        steps:
            - checkout
            - run: make
            - store_artifacts:
                path: rules.pdf
                destination: rules.pdf
